apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-incident-demo
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: pacman-cilium-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pacman
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pacman
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: pacman-cilium-demo
    spec:
      containers:
        - name: pacman
          image: docker.io/saintdle/pacman@sha256:cb9272461127465676fefd4778e67faea41ef65e03c19014626287d2c542dd05
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: incident-demo
            - name: APP_VARIANT
              value: suspicious-score
            - name: DB_TYPE
              value: memory
            - name: DEMO_SECURITY_MODE
              value: "true"
            - name: DEMO_TOKEN
              value: pacman-demo
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-incident-demo
spec:
  selector:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
