apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret          # the Secret your Deployment references
  namespace: pacman
type: Opaque
stringData:
  database-name: "pacman"
  database-user: "pacman"             # must match the Mongo user created on the VM
  database-admin-name: "admin"
  database-password: "${MONGODB_APP_PWD}"        # from /wiz-panel/dev/mongodb/appPwd