apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pacman
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  selector:
    name: mongo
